sudo: false
language: node_js
node_js:
- '10'
cache: npm
services:
- docker
env:
  global:
  - NODE_ENV=CI
stages:
- install
- test
- build
jobs:
  include:
  - stage: install
    script:
    - yarn install
  - stage: test
    script:
    - yarn run coveralls
  - stage: build
    script:
      - yarn build
      - rm -rf node_modules
      - yarn install --production --ignore-scripts
      - docker build -t travis-ci-build-stage -f Dockerfile.ci .
      - docker tag travis-ci-build-stage gcr.io/$GC_PROJECT_ID/eve-api:$TRAVIS_BUILD_NUMBER
      - openssl aes-256-cbc -K $encrypted_571ea1114113_key -iv $encrypted_571ea1114113_iv -in gce.json.enc -out gce.json -d
      - cat gce.json | docker login -u _json_key --password-stdin https://gcr.io
      - docker push gcr.io/$GC_PROJECT_ID/eve-api:$TRAVIS_BUILD_NUMBER
    if: "(branch = dev OR branch = master) AND type = push"
