runtime: nodejs12
service: eve-mate-api
env: flex

manual_scaling:
  instances: 1

beta_settings:
  cloud_sql_instances: personal-248114:us-east1:eve-kit-pd

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  APP_ENGINE: 'true'
  SENTRY_DSN: 'https://3df90faaa98c4caf84cd615965e4aa42@sentry.io/1816282'
