FROM launcher.gcr.io/google/nodejs

RUN install_node v12

WORKDIR /usr/src/app

ENV SCHEMA_LOCATION ./schema

COPY package.json .
COPY build ./build
COPY node_modules ./node_modules

EXPOSE 4000
CMD [ "npm", "start" ]
