apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eve-api.name" . }}-secret
  labels:
  {{ include "eve-api.labels" . | indent 4 }}
type: Opaque
data:
  {{ if .Values.dbPassword }}
  db-psw: {{ .Values.dbPassword | b64enc | quote }}
  {{ else }}
  db-psw: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.redisPassword }}
  redis-psw: {{ .Values.redisPassword | b64enc | quote }}
  {{ else }}
  redis-psw: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.eveClientSecret }}
  eve-client-secret: {{ .Values.eveClientSecret | b64enc | quote }}
  {{ else }}
  eve-client-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.tokenSecret }}
  token-secret: {{ .Values.tokenSecret | b64enc | quote }}
  {{ else }}
  token-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
