version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: node:16.18.1-bullseye-slim
    working_directory: ~/eve-api
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run tests
          command: yarn test
      - store_test_results:
          path: .
      - setup_remote_docker:
          docker_layer_caching: true
      - coveralls/upload
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t dariusbakunas/eve-api:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push dariusbakunas/eve-api:$TAG

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}

workflows:
  build_and_report:
    jobs:
      - build