version: 2
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t dariusbakunas/eve-api:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push dariusbakunas/eve-api:$TAG
      - coveralls/upload