import * as Knex from 'knex';

export async function seed(knex: Knex): Promise<any> {
  // Deletes ALL existing entries
  return knex('scopes')
    .del()
    .then(() => {
      // Inserts seed entries
      return knex('scopes').insert([
        { id: 1, name: 'esi-alliances.read_contacts.v1' },
        { id: 2, name: 'esi-assets.read_assets.v1' },
        { id: 3, name: 'esi-assets.read_corporation_assets.v1' },
        { id: 4, name: 'esi-bookmarks.read_character_bookmarks.v1' },
        { id: 5, name: 'esi-bookmarks.read_corporation_bookmarks.v1' },
        { id: 6, name: 'esi-calendar.read_calendar_events.v1' },
        { id: 7, name: 'esi-calendar.respond_calendar_events.v1' },
        { id: 8, name: 'esi-characters.read_agents_research.v1' },
        { id: 9, name: 'esi-characters.read_blueprints.v1' },
        { id: 10, name: 'esi-characters.read_contacts.v1' },
        { id: 11, name: 'esi-characters.read_corporation_roles.v1' },
        { id: 12, name: 'esi-characters.read_fatigue.v1' },
        { id: 13, name: 'esi-characters.read_fw_stats.v1' },
        { id: 14, name: 'esi-characters.read_loyalty.v1' },
        { id: 15, name: 'esi-characters.read_medals.v1' },
        { id: 16, name: 'esi-characters.read_notifications.v1' },
        { id: 17, name: 'esi-characters.read_opportunities.v1' },
        { id: 18, name: 'esi-characters.read_standings.v1' },
        { id: 19, name: 'esi-characters.read_titles.v1' },
        { id: 20, name: 'esi-characters.write_contacts.v1' },
        { id: 21, name: 'esi-characterstats.read.v1' },
        { id: 22, name: 'esi-clones.read_clones.v1' },
        { id: 23, name: 'esi-clones.read_implants.v1' },
        { id: 24, name: 'esi-contracts.read_character_contracts.v1' },
        { id: 25, name: 'esi-contracts.read_corporation_contracts.v1' },
        { id: 26, name: 'esi-corporations.read_blueprints.v1' },
        { id: 27, name: 'esi-corporations.read_contacts.v1' },
        { id: 28, name: 'esi-corporations.read_container_logs.v1' },
        { id: 29, name: 'esi-corporations.read_corporation_membership.v1' },
        { id: 30, name: 'esi-corporations.read_divisions.v1' },
        { id: 31, name: 'esi-corporations.read_facilities.v1' },
        { id: 32, name: 'esi-corporations.read_fw_stats.v1' },
        { id: 33, name: 'esi-corporations.read_medals.v1' },
        { id: 34, name: 'esi-corporations.read_standings.v1' },
        { id: 35, name: 'esi-corporations.read_starbases.v1' },
        { id: 36, name: 'esi-corporations.read_structures.v1' },
        { id: 37, name: 'esi-corporations.read_titles.v1' },
        { id: 38, name: 'esi-corporations.track_members.v1' },
        { id: 39, name: 'esi-fittings.read_fittings.v1' },
        { id: 40, name: 'esi-fittings.write_fittings.v1' },
        { id: 41, name: 'esi-fleets.read_fleet.v1' },
        { id: 42, name: 'esi-fleets.write_fleet.v1' },
        { id: 43, name: 'esi-industry.read_character_jobs.v1' },
        { id: 44, name: 'esi-industry.read_character_mining.v1' },
        { id: 45, name: 'esi-industry.read_corporation_jobs.v1' },
        { id: 46, name: 'esi-industry.read_corporation_mining.v1' },
        { id: 47, name: 'esi-killmails.read_corporation_killmails.v1' },
        { id: 48, name: 'esi-killmails.read_killmails.v1' },
        { id: 49, name: 'esi-location.read_location.v1' },
        { id: 50, name: 'esi-location.read_online.v1' },
        { id: 51, name: 'esi-location.read_ship_type.v1' },
        { id: 52, name: 'esi-mail.organize_mail.v1' },
        { id: 53, name: 'esi-mail.read_mail.v1' },
        { id: 54, name: 'esi-mail.send_mail.v1' },
        { id: 55, name: 'esi-markets.read_character_orders.v1' },
        { id: 56, name: 'esi-markets.read_corporation_orders.v1' },
        { id: 57, name: 'esi-markets.structure_markets.v1' },
        { id: 58, name: 'esi-planets.manage_planets.v1' },
        { id: 59, name: 'esi-planets.read_customs_offices.v1' },
        { id: 60, name: 'esi-search.search_structures.v1' },
        { id: 61, name: 'esi-skills.read_skillqueue.v1' },
        { id: 62, name: 'esi-skills.read_skills.v1' },
        { id: 63, name: 'esi-ui.open_window.v1' },
        { id: 64, name: 'esi-ui.write_waypoint.v1' },
        { id: 65, name: 'esi-universe.read_structures.v1' },
        { id: 66, name: 'esi-wallet.read_character_wallet.v1' },
        { id: 67, name: 'esi-wallet.read_corporation_wallets.v1' },
      ]);
    });
}
