apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: production-
commonLabels:
  variant: production

bases:
  - ../../base

images:
  - name: eve-api-image
    newTag: a11c7662e4f0c8fdec5f69650d23f77577b9064d48ee255d18aa9fcd2ff6ca21
    newName: gcr.io/personal-248114/eve-api@sha256

secretGenerator:
  - name: eve-warehouse-api-secret
    envs:
      - secrets.env

patchesStrategicMerge:
  - custom-env.yaml
