---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eve-warehouse-api
  labels:
    account: eve-warehouse-api
imagePullSecrets:
  - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: eve-warehouse-api
  labels:
    service: eve-warehouse-api
spec:
  ports:
    - port: 4000
      name: http
