name: CI

on:
  push:
    branches:
      - release

env:
  GC_PROJECT_ID: ${{ secrets.GC_PROJECT_ID }}
  IMAGE: eve-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '278.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: gcloud Set up
        run: |
          gcloud config set project $GC_PROJECT_ID
      - run: |
          gcloud app deploy