name: CI

on:
  push:
    branches:
      - release

env:
  GC_PROJECT_ID: ${{ secrets.GC_PROJECT_ID }}
  IMAGE: eve-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: $GC_PROJECT_ID
      - name: gcloud Set up
        run: |
          gcloud config set project $GC_PROJECT_ID
      - run: |
          gcloud app deploy
