apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-warehouse-api-v1
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: LOG_LEVEL
              value: debug
